"""Contextual Enrichment — §8.2.2 (Anthropic Contextual Retrieval).

Each chunk is enriched with a contextual preamble that explains where
the chunk sits within the broader document.  This dramatically improves
both embedding quality and BM25 keyword matching.

When an ``llm_client`` is available the preamble is generated by the LLM
(Anthropic's method).  When not, a heuristic preamble is constructed
from document metadata.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ppt_agent.llm.client import LLMClient

logger = logging.getLogger(__name__)

_ENRICH_SYSTEM = (
    "You are a document context annotator.  Given a document chunk and "
    "optional metadata, write a 1-2 sentence contextual preamble that "
    "explains where this chunk sits within the document and what topic "
    "it covers.  This preamble will be prepended to the chunk to improve "
    "retrieval.  Respond with ONLY the preamble text — no labels, no "
    "markdown, no explanation."
)


def enrich_chunk(
    text: str,
    context: str = "",
    *,
    document_name: str = "",
    chunk_index: int = 0,
    total_chunks: int = 0,
    doc_type: str = "",
    llm_client: "LLMClient | None" = None,
) -> str:
    """Enrich a chunk with a contextual preamble.

    Parameters
    ----------
    text
        The original chunk text.
    context
        Optional pre-existing context string (used as-is if no LLM).
    document_name
        Name of the source document.
    chunk_index
        Zero-based position of this chunk within the document.
    total_chunks
        Total number of chunks in the document.
    doc_type
        Detected document type (``"markdown"``, ``"code"``, …).
    llm_client
        Optional LLM client for LLM-based enrichment.

    Returns the enriched text: ``[Preamble]\\n[Original Chunk]``.
    """
    if llm_client is not None:
        preamble = _llm_enrich(
            text, llm_client,
            document_name=document_name,
            chunk_index=chunk_index,
            total_chunks=total_chunks,
            doc_type=doc_type,
        )
        if preamble:
            return f"{preamble}\n{text}"

    # Heuristic or explicit-context fallback
    if context:
        return f"{context}\n{text}".strip()

    preamble = _heuristic_preamble(
        document_name=document_name,
        chunk_index=chunk_index,
        total_chunks=total_chunks,
        doc_type=doc_type,
        text=text,
    )
    if preamble:
        return f"{preamble}\n{text}"
    return text


def _llm_enrich(
    text: str,
    llm_client: "LLMClient",
    *,
    document_name: str = "",
    chunk_index: int = 0,
    total_chunks: int = 0,
    doc_type: str = "",
) -> str:
    """Generate a contextual preamble via LLM (Anthropic method)."""
    meta_parts: list[str] = []
    if document_name:
        meta_parts.append(f"Document: {document_name}")
    if doc_type:
        meta_parts.append(f"Type: {doc_type}")
    if total_chunks > 0:
        meta_parts.append(f"Chunk {chunk_index + 1} of {total_chunks}")
    meta = "; ".join(meta_parts)

    prompt = f"Metadata: {meta}\n\nChunk content:\n{text[:2000]}"
    try:
        preamble = llm_client.generate_text(
            prompt=prompt,
            system=_ENRICH_SYSTEM,
            temperature=0.0,
            max_tokens=150,
        ).strip()
        return preamble
    except Exception:
        logger.warning("LLM enrichment failed, using heuristic", exc_info=True)
        return ""


def _heuristic_preamble(
    *,
    document_name: str = "",
    chunk_index: int = 0,
    total_chunks: int = 0,
    doc_type: str = "",
    text: str = "",
) -> str:
    """Build a contextual preamble from available metadata."""
    parts: list[str] = []

    if document_name:
        parts.append(f"This chunk is from {document_name}")

    if total_chunks > 1:
        position_desc = "beginning" if chunk_index == 0 else (
            "end" if chunk_index == total_chunks - 1 else "middle"
        )
        parts.append(f"located in the {position_desc} of the document (chunk {chunk_index + 1}/{total_chunks})")
    elif chunk_index > 0:
        parts.append(f"chunk {chunk_index + 1} of the document")

    if doc_type:
        type_labels = {
            "markdown": "a Markdown section",
            "code": "a source code block",
            "json": "a JSON data structure",
            "text": "a text passage",
        }
        type_label = type_labels.get(doc_type, "a document section")
        parts.append(f"containing {type_label}")

    if not parts:
        return ""

    # Capitalise first letter, end with period
    preamble = ", ".join(parts) + "."
    return preamble[0].upper() + preamble[1:]
